# Generated by Django 5.2.7 on 2025-10-14 18:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecollection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description of what this collection does', null=True),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description of what this playbook does', null=True),
        ),
        migrations.AddField(
            model_name='ansiblerole',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description of what this role does', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description of this file', null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description of what this script does', null=True),
        ),
    ]
